//Logowanie Szyfrowane z pliku zaszyfrowanego (funkcja fnSzyfrowanie) ../User/Login.txt za pomoc¹ funkcji fnLogowanie();
//Menu Glowne wywolane z funkcji fnMainMenu();
//Wylogowywanie za pomocą "skoku" ( login: ) do funkcji fnLogowanie();
//Rejestracja nowego "uzytkownika" za pomoca funkcji fnRegister();

//Dodawanie nowego pliku "bazy" za pomoca funkcji fnCreate();
//Wczytywanie pliku za pomoca funkcji fnLoad();
//Aktualizowanie rekordu za pomocą funkcji fnUpdate();
//Usuwanie rekordu za pomoca funkcji fnDelete();
//Szukanie rekordu po: imieniu lub nazwisku lub pesel lub stanowisku lub pensji za pomocą funkcji fnFind();
//Zawartosc pliku wyswietlana za pomoca funkcji fnShow();
//Nowe Bazy i Bazy które chcemy dodać do programu muszą znajdować się w folderze "DoWczytania"
//Wyswietlanie zawartosci bazy za pomoca funkcji Show();
